AppBundle\Entity\Modflag:
    type: entity
    table: modflags
    oneToMany:
        decklists:
            targetEntity: Decklist
            mappedBy: modflag
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        reason:
            type: string
            length: 255
    lifecycleCallbacks: {  }
